# Generated by Django 4.2.3 on 2023-07-10 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayzeCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_mask', models.CharField(blank=True, max_length=20, null=True)),
                ('card_brand', models.CharField(blank=True, max_length=20, null=True)),
                ('card_holder', models.CharField(blank=True, max_length=30, null=True)),
                ('expire_date', models.CharField(blank=True, max_length=5, null=True)),
                ('card_token', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('payment_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='card.paymentid')),
            ],
        ),
    ]
