# Generated by Django 4.2.5 on 2024-01-20 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Full Name')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Payer',
                'verbose_name_plural': 'Payers',
                'db_table': 'card_payer',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_id', models.IntegerField(verbose_name='Card ID')),
                ('order_id', models.IntegerField(null=True, verbose_name='Order ID')),
                ('commission', models.IntegerField(default=0, null=True, verbose_name='Commission')),
                ('invoice', models.CharField(max_length=255, verbose_name='Invoice')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('final_amount', models.FloatField(blank=True, default=0, null=True, verbose_name='Final Amount')),
                ('debt', models.FloatField(default=0, verbose_name='Debt')),
                ('credit', models.FloatField(default=0, verbose_name='Credit')),
                ('reason', models.IntegerField(choices=[(1, 'ORDER'), (2, 'DEBT'), (3, 'TIP'), (4, 'CARD_VERIFY')], verbose_name='Reason')),
                ('currency', models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], max_length=40, verbose_name='Currency')),
                ('provider_type', models.CharField(choices=[('Payze', 'PAYZE')], max_length=40, verbose_name='Provider Type')),
                ('status', models.CharField(choices=[('Pending', 'PENDING'), ('Succeeded', 'SUCCESS'), ('Rejected', 'REJECTED')], default='Pending', max_length=40, verbose_name='Status')),
                ('idempotency_key', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Idempotency Key')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_id', models.CharField(verbose_name='Payment ID')),
                ('number', models.CharField(blank=True, max_length=18, null=True, verbose_name='Number')),
                ('expire_date', models.CharField(blank=True, max_length=5, null=True, verbose_name='Expire Date')),
                ('token', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Token')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('entity_type', models.CharField(default='Unknown', max_length=100, verbose_name='Entity Type')),
                ('brand_types', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand Types')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payer', verbose_name='Payer')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'db_table': 'cards',
            },
        ),
    ]
