# Generated by Django 4.2.5 on 2024-01-18 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardVerifyPayment',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Payment ID')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('currency', models.CharField(blank=True, max_length=16, null=True, verbose_name='Currency')),
                ('payment_status', models.CharField(max_length=16, verbose_name='Payment Status')),
                ('idempotency_key', models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Idempotency Key')),
                ('final_amount', models.FloatField(default=0, verbose_name='Amount')),
            ],
            options={
                'db_table': 'card_verify_payments',
            },
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=16, null=True, verbose_name='Number')),
                ('expire_date', models.CharField(blank=True, max_length=5, null=True, verbose_name='Expire Date')),
                ('holder', models.CharField(blank=True, max_length=100, null=True, verbose_name='Holder')),
                ('cvv', models.CharField(blank=True, max_length=3, null=True, verbose_name='CVV')),
                ('token', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Token')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('entity_type', models.CharField(default='Unknown', max_length=100, verbose_name='Entity Type')),
                ('brand_types', models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand Types')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Card Types')),
                ('very_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.cardverifypayment', verbose_name='Very Payment')),
            ],
            options={
                'db_table': 'cards',
            },
        ),
    ]
