# Generated by Django 4.2.5 on 2024-01-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='number',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='cardverifypayment',
            name='currency',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='cardverifypayment',
            name='final_amount',
            field=models.FloatField(default=0, verbose_name='Final Amount'),
        ),
        migrations.AlterField(
            model_name='cardverifypayment',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Idempotency Key'),
        ),
    ]
