# Generated by Django 4.2.5 on 2024-01-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_cards_number_alter_cardverifypayment_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardverifypayment',
            name='final_amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Final Amount'),
        ),
    ]
