# Generated by Django 4.2.5 on 2024-01-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_cards_brand_types_alter_cards_entity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='credit',
            field=models.FloatField(default=0, null=True, verbose_name='Credit'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='debt',
            field=models.FloatField(default=0, null=True, verbose_name='Debt'),
        ),
    ]
