# Generated by Django 4.2.5 on 2024-01-18 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payer_cards_payer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='cvv',
        ),
    ]
