# Generated by Django 4.2.5 on 2024-01-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_cards_cvv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='very_payment',
            new_name='verify_payment',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='holder',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='type',
        ),
    ]
